const String success = "the request was successful";
// error handler
const String noInternetError = "Connection Error: No Internet Connection";
const String badRequestError =
    "the server cannot or will not process the request due to a client error";
const String badResponseError =
    "the server cannot or will not process the request due to an internal error";
const String badCertificateError =
    "The request was cancelled due to a cache error";
const String noContentError =
    "the requested resource could not be found but may be available in the future";
const String forbiddenError =
    "the request is being rejected due to the user not having the necessary permissions";
const String unauthorizedError =
    " the request is being rejected due to the user not being authenticated";
const String notFoundError = "the requested resource could not be found";
const String conflictError =
    "the request was cancelled due to a conflict error";
const String internalServerError =
    " unexpected condition was encountered and no more specific message is suitable";
const String strUnknownError = "unknown_error";
const String receivingTimeout = "receiving data from the API timed out";
const String sendingTimeout = "sending data to the API timed out";
const String connectionTimeout = "the connection to the API timed out";
const String connectionError =
    "The connection errored and the request could not be completed: Failed host lookup";
const String defaultError =
    "the server cannot or will not process the request due to an internal error";
const String cacheError =
    "the request could not be completed due to a cache error";
const String cancelError = "The request was cancelled";
